# Generated by Django 4.2.5 on 2024-02-15 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParkerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='login_table',
        ),
    ]
