# Generated by Django 4.2.5 on 2024-02-28 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParkerApp', '0003_register_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register_model',
            new_name='register_table',
        ),
    ]
