# Generated by Django 4.2.5 on 2024-02-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParkerApp', '0004_rename_register_model_register_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_table',
            name='username',
        ),
    ]
