# Generated by Django 4.2.5 on 2024-03-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParkerApp', '0005_remove_register_table_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_table',
        ),
    ]
