# Generated by Django 4.2.5 on 2024-03-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkerApp', '0008_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
