# Generated by Django 4.2.5 on 2024-03-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkerApp', '0009_reservation_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment',
            field=models.CharField(choices=[('credit', 'Credit Card'), ('debit', 'Debit Card'), ('paypal', 'PayPal')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
