# Generated by Django 4.2.5 on 2024-04-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkerApp', '0010_reservation_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Paypal', 'PayPal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
