# Generated by Django 4.2.5 on 2024-04-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkerApp', '0011_alter_reservation_payment_alter_reservation_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment',
            field=models.CharField(choices=[('Credit Card', 'credit'), ('Debit Card', 'debit'), ('PayPal', 'paypal')], max_length=20),
        ),
    ]
