# Generated by Django 4.2.5 on 2024-05-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkerApp', '0013_remove_reservation_payment_reservation_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
