# Generated by Django 4.2.5 on 2024-06-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkerApp', '0014_reservation_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
