# Generated by Django 4.2.5 on 2024-06-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkerApp', '0015_alter_reservation_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_slots', models.IntegerField()),
                ('reserved_slots', models.IntegerField()),
            ],
        ),
    ]
