# Generated by Django 4.2.5 on 2024-06-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkerApp', '0016_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='location',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
