# Generated by Django 4.2.5 on 2024-06-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParkerApp', '0017_slots_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='slots',
            new_name='slots_table',
        ),
    ]
