# Generated by Django 4.2.5 on 2024-06-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkerApp', '0019_alter_reservation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots_table',
            name='location',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
