# Generated by Django 4.2.5 on 2024-06-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkerApp', '0021_subscribers_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers_table',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
