# Generated by Django 5.0.6 on 2024-07-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkerApp', '0025_alter_subscribers_table_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots_table',
            name='max_slots',
            field=models.IntegerField(default=40),
        ),
    ]
