# Generated by Django 5.0.6 on 2024-07-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkerApp', '0026_slots_table_max_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers_table',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
