# Generated by Django 5.0.6 on 2024-07-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkerApp', '0028_feedback_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_table',
            name='rating',
            field=models.IntegerField(max_length=1),
        ),
    ]
