# Generated by Django 5.0.6 on 2024-07-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkerApp', '0029_alter_feedback_table_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_table',
            name='experience',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback_table',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
