# Generated by Django 5.0.6 on 2024-07-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkerApp', '0030_alter_feedback_table_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_table',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
