# Generated by Django 5.0.6 on 2024-07-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkerApp', '0032_alter_feedback_table_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_table',
            name='experience',
            field=models.TextField(),
        ),
    ]
