# Generated by Django 5.0.6 on 2024-07-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkerApp', '0033_alter_feedback_table_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_table',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='feedback_table',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
    ]
