# Generated by Django 5.0.6 on 2024-07-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkerApp', '0034_feedback_table_email_feedback_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_table',
            name='email',
            field=models.EmailField(default='email.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='feedback_table',
            name='name',
            field=models.CharField(default='Name', max_length=100),
        ),
    ]
